### ISSUE TITLE
Air launch Limits should be based on Player Skill

### ISSUE THREAD

**Issue by wldarden** [KSP-RO/RP-1#2284]
Currently, maximum air launch speed, altitude, distance, etc. is controlled through research upgrades. It would be very cool to let the player build their own air launch vehicle, and increase those maximum limits based on completing optional contracts.

- I would keep the current research controlled limits for players that don't want to mess with this. If the player never wants to build a carrier vehicle they don't have to, they can just use the current "research unlock" system as is. so this idea isn't a replacement, its just another option for players who want to do it.
- I would ADD new, optional, "Air Launch Vehicle Development" contracts to the "X-plane Research" Program. The requirements for the contract would be to carry some mass in level flight at some altitude at some speed for an amount of time. I would implement this system with one of the following options:

Option 1: (coolest) If players can set their own objective values for these contracts, that would be awesome. for example, if I need to lift 30t instead of 25t, but the altitude and speed aren't important to me, I would create and accept a new "Air Launch Vehicle Development" contract with the same 13750m and 272m/s values, but increase 25t to 30t. On completion my new maximum AL mass would be 30t, I could focus on the values that matter to me. 

Option 2: (most reasonable) If players can't set their own contract objective values, maybe optional objectives similar to the "land on the runway with descent angle lower than 10 degrees" ones could be used to increase each stat individually. For example, the "Air Launch Vehicle Development" contract would have objectives like:
```
Objectives:
  Required: altitude (current max)
      Optional: altitude (current max + 10% or 5k)
  Required: sounding payload(current max)
      Optional: sounding payload (current max + 10% or 5t)
  Required: speed (current max)
      Optional: speed (current max + 10% or 100m/s or 50m/s)

  Required: level flight for 2 minutes
  Required: Takeoff from runway (cant air launch your air launch...)
  Required: Reach 100km down range (or something to show that your craft can carry the mass long enough to launch it and return safely. Could be a time or distance requirement)
  Required: Land on the runway
  
```
Option 3: (least favorite) there could be lots of available optional contracts that are hardcoded with different permutations... this would be messy though. even if there were only one available contract per air launch stat, completing them individually could be annoying/time consuming, while only providing one contract where every stat has to be increased simultaneously (instead of optionally like in option 2) might be too hard, and the player might not need all the stats to increase.

Why this should happen/Why its cool:
- The player is responsible for their own limitations. They aren't arbitrarily restricted to "272 m/s at 13750m up to 25t" because "the game says so" or the research node they're on, They're only limited by their own ability to design and fly crafts!
- The costs of building and launching the plane to complete these contracts is like real life RnD costs!
- It will only affect players who care about it. The original system will still be in place, similar to "contracting out the air launch development process to a 3rd party". BUT, for people who find it fun and useful, they can be responsible for their own limits!
- The current restrictions feel arbitrary. Cant do anything about them except wait for research. I've built my own air launch vehicles that detach smaller craft for them to higher than the air launch limits, but I lose the carrier plane because I cant fly 2 at once. this is arbitrary, its a restriction for technical reasons, not realistic game reasons. In real life Id have 2 pilots. this is the best we can do to simulate that.
